version: '3.5'

services:
  src:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-manager
    ports:
      - '3000:3000'
    volumes:
      - .:/src
      - /src/node_modules
